In [23]:
# import libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [24]:
url_rt3 = './data/tmdb.movies.csv.gz'
tmdb_movies = pd.read_csv(url_rt3)

In [25]:
url_rt4 = './data/tn.movie_budgets.csv.gz'
tmdb_budgets = pd.read_csv(url_rt4)

In [26]:
# add year & month 
tmdb_movies['date'] = pd.to_datetime(tmdb_movies['release_date'])
tmdb_movies['year'] = tmdb_movies['date'].dt.year
tmdb_movies['month']= tmdb_movies['date'].dt.month

tmdb_budgets['date'] = pd.to_datetime(tmdb_budgets['release_date'])
tmdb_budgets['year'] = tmdb_budgets['date'].dt.year
tmdb_budgets['month'] = tmdb_budgets['date'].dt.month

# slice tmdb_movies (year 2010-2019)
mask = (tmdb_movies['year']<=2019) & (tmdb_movies['year']>=2010)
tmdb_movies = tmdb_movies.loc[mask].copy()

# slicing dataset 2010-2019
mask = (tmdb_budgets['year']<=2019) & (tmdb_budgets['year']>=2010)
tmdb_budgets = tmdb_budgets.loc[mask].copy()

In [27]:
import string
def str_num(s):
    ''' convert s to a list of numbers
        example: 
        input: s = '[12, 14, 10751]'
        output: [12, 14, 10751]   
    '''
    # strip all punctuation from a string 
    s = s.translate(str.maketrans('', '', string.punctuation))
    # string to list 
    #s_list = [int(n) for n in s.split()]
    return s.split()

In [28]:
# 1. covert genre_ids [12, 14, 10751] in to columns
tmdb_movies['genre_ids'] = tmdb_movies['genre_ids'].apply(str_num)

In [29]:
tmdb_movies.columns

Index(['Unnamed: 0', 'genre_ids', 'id', 'original_language', 'original_title',
       'popularity', 'release_date', 'title', 'vote_average', 'vote_count',
       'date', 'year', 'month'],
      dtype='object')

In [30]:
cols = ['genre_ids','original_title','title', 'vote_average', 'vote_count','popularity','date', 'year', 'month','original_language']
tmdb_movies_genre = tmdb_movies[cols].copy()

In [31]:
cols_var = ['original_title','title', 'vote_average', 'vote_count','popularity','date', 'year', 'month','original_language']
tmdb_movies_genre = tmdb_movies_genre['genre_ids'].apply(pd.Series).merge(tmdb_movies_genre, left_index = True, right_index = True)\
.drop(["genre_ids"], axis = 1).melt(id_vars = cols_var, value_name = "genre")

In [35]:
# drop col variable 
tmdb_movies_genre.drop(columns=['variable'], inplace = True)

In [37]:
# drop rows with genre NaN 
tmdb_movies_genre.dropna(subset = ['genre'], inplace = True)

In [40]:
tmdb_genres=[{'id': 28, 'name': 'Action'},
            {'id': 12, 'name': 'Adventure'},
            {'id': 16, 'name': 'Animation'},
            {'id': 35, 'name': 'Comedy'},
            {'id': 80, 'name': 'Crime'},
            {'id': 99, 'name': 'Documentary'},
            {'id': 18, 'name': 'Drama'},
            {'id': 10751, 'name': 'Family'},
            {'id': 14, 'name': 'Fantasy'},
            {'id': 36, 'name': 'History'},
            {'id': 27, 'name': 'Horror'},
            {'id': 10402, 'name': 'Music'},
            {'id': 9648, 'name': 'Mystery'},
            {'id': 10749, 'name': 'Romance'},
            {'id': 878, 'name': 'Science Fiction'},
            {'id': 10770, 'name': 'TV Movie'},
            {'id': 53, 'name': 'Thriller'},
            {'id': 10752, 'name': 'War'},
            {'id': 37, 'name': 'Western'}]

In [43]:
# mapping genres_id to genre

# 1. create a dict with {id_value1:genre1, id_value2:genre2} from tmdb_genres
genre_dict = {}
for pair in tmdb_genres:
    genre_dict[pair['id']] = pair['name']
genre_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [48]:
# 'genre' col has dtype (O), convert to int 
tmdb_movies_genre['genre'] = tmdb_movies_genre['genre'].astype(int)

In [49]:
# check 
tmdb_movies_genre['genre'].dtype

dtype('int64')

In [50]:
# map genre_id to genre 
tmdb_movies_genre['genre'] = tmdb_movies_genre['genre'].map(genre_dict)

- Check target result

In [38]:
# Check target result

# check and compare with movie '"BLESSED"'
mask = tmdb_movies['title'] =='"BLESSED"'
tmdb_movies[mask]

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,date,year,month
26355,26355,"[99, 12]",564096,en,"""BLESSED""",0.6,2018-11-23,"""BLESSED""",7.0,1,2018-11-23,2018,11

In [51]:
# Check target result

tmdb_movies_genre.sort_values('title', axis=0)

,original_title,title,vote_average,vote_count,popularity,date,year,month,original_language,genre
26129,"""BLESSED""","""BLESSED""",7.0,1,0.600,2018-11-23,2018,11,en,Documentary
52419,"""BLESSED""","""BLESSED""",7.0,1,0.600,2018-11-23,2018,11,en,Adventure
33992,"""Legitimate Rape"" Pharmaceutical Ad","""Legitimate Rape"" Pharmaceutical Ad",2.3,2,0.600,2012-08-28,2012,8,en,Crime
7702,"""Legitimate Rape"" Pharmaceutical Ad","""Legitimate Rape"" Pharmaceutical Ad",2.3,2,0.600,2012-08-28,2012,8,en,Comedy
12661,"""cherry"" - Supreme","""cherry"" - Supreme",10.0,1,0.893,2014-03-20,2014,3,en,Documentary
549,#1 Cheerleader Camp,#1 Cheerleader Camp,3.6,34,3.277,2010-07-27,2010,7,en,Comedy
26839,#1 Cheerleader Camp,#1 Cheerleader Camp,3.6,34,3.277,2010-07-27,2010,7,en,Drama
15871,#ALLMYMOVIES,#ALLMYMOVIES,9.0,4,0.840,2015-11-12,2015,11,en,Documentary
21955,#Captured,#Captured,3.2,6,1.418,2017-10-11,2017,10,en,Horror
18541,#FollowFriday,#FollowFriday,3.2,7,1.646,2016-07-01,2016,7,en,Thriller
48964,#FromJennifer,#FromJennifer,4.0,2,0.677,2017-09-26,2017,9,en,Comedy
75254,#FromJennifer,#FromJennifer,4.0,2,0.677,2017-09-26,2017,9,en,Horror
22674,#FromJennifer,#FromJennifer,4.0,2,0.677,2017-09-26,2017,9,en,Thriller
93363,#Horror,#Horror,3.3,102,6.099,2015-11-20,2015,11,de,Thriller
40783,#Horror,#Horror,3.3,102,6.099,2015-11-20,2015,11,de,Mystery
14493,#Horror,#Horror,3.3,102,6.099,2015-11-20,2015,11,de,Drama
67073,#Horror,#Horror,3.3,102,6.099,2015-11-20,2015,11,de,Horror
15778,#Introductions,#Introductions,7.8,9,0.918,2015-06-03,2015,6,en,Drama
15775,#Lucky Number,#Lucky Number,6.0,2,0.919,2015-09-01,2015,9,en,Comedy
38243,#PopFan,#PopFan,4.1,10,2.121,2014-08-23,2014,8,en,Mystery
64533,#PopFan,#PopFan,4.1,10,2.121,2014-08-23,2014,8,en,Thriller
11953,#PopFan,#PopFan,4.1,10,2.121,2014-08-23,2014,8,en,Drama
35487,#PostModem,#PostModem,5.5,3,1.274,2013-01-18,2013,1,en,Music
9197,#PostModem,#PostModem,5.5,3,1.274,2013-01-18,2013,1,en,Science Fiction
61777,#PostModem,#PostModem,5.5,3,1.274,2013-01-18,2013,1,en,Comedy
20546,#RealityHigh,#RealityHigh,6.4,703,13.629,2017-07-17,2017,7,en,Comedy
51203,#Roxy,#Roxy,4.0,3,2.750,2018-04-13,2018,4,en,Romance
24913,#Roxy,#Roxy,4.0,3,2.750,2018-04-13,2018,4,en,Comedy
19205,#Rucker50,#Rucker50,3.7,3,0.840,2016-12-28,2016,12,en,Documentary
18520,#SCREAMERS,#SCREAMERS,3.8,5,1.688,2016-10-14,2016,10,en,Horror
...,...,...,...,...,...,...,...,...,...,...
7120,nWo: The Revolution,nWo: The Revolution,7.7,3,0.600,2012-11-06,2012,11,en,Documentary
19640,scratch on metal,scratch on metal,10.0,1,0.600,2016-05-01,2016,5,en,Drama
45930,scratch on metal,scratch on metal,10.0,1,0.600,2016-05-01,2016,5,en,Family
4616,small roads,small roads,6.5,4,0.600,2011-09-03,2011,9,en,Documentary
36801,spanners,spanners,5.0,1,0.600,2013-01-01,2013,1,en,Mystery
10511,spanners,spanners,5.0,1,0.600,2013-01-01,2013,1,en,Fantasy
63091,spanners,spanners,5.0,1,0.600,2013-01-01,2013,1,en,Science Fiction
1006,La toute dernière,the final girl,6.1,8,1.462,2010-08-31,2010,8,fr,Drama
15853,unReal,unReal,7.3,6,0.846,2015-07-01,2015,7,en,Documentary
42143,unReal,unReal,7.3,6,0.846,2015-07-01,2015,7,en,Comedy
38238,uwantme2killhim?,uwantme2killhim?,6.6,28,2.143,2014-03-14,2014,3,en,Thriller
11948,uwantme2killhim?,uwantme2killhim?,6.6,28,2.143,2014-03-14,2014,3,en,Drama
20462,xXx: Return of Xander Cage,xXx: Return of Xander Cage,5.6,2452,21.749,2017-01-20,2017,1,en,Action
73042,xXx: Return of Xander Cage,xXx: Return of Xander Cage,5.6,2452,21.749,2017-01-20,2017,1,en,Crime
46752,xXx: Return of Xander Cage,xXx: Return of Xander Cage,5.6,2452,21.749,2017-01-20,2017,1,en,Adventure
6614,¡Cuatro!,¡Cuatro!,7.0,4,0.840,2012-11-28,2012,11,en,Music
32904,¡Cuatro!,¡Cuatro!,7.0,4,0.840,2012-11-28,2012,11,en,Documentary
52259,ÉG,ÉG,10.0,1,0.600,2018-03-21,2018,3,en,Drama
25969,ÉG,ÉG,10.0,1,0.600,2018-03-21,2018,3,en,Family
26207,メタフィクション - (M E T A F I C T I O N),メタフィクション - (M E T A F I C T I O N),5.5,2,0.600,2018-08-16,2018,8,en,Comedy
19562,洛杉矶捣蛋计划,洛杉矶捣蛋计划,8.0,1,0.634,2016-03-18,2016,3,zh,Comedy
58437,纽约客@上海,纽约客@上海,6.0,12,2.416,2012-05-03,2012,5,zh,Drama
5857,纽约客@上海,纽约客@上海,6.0,12,2.416,2012-05-03,2012,5,zh,Romance
32147,纽约客@上海,纽约客@上海,6.0,12,2.416,2012-05-03,2012,5,zh,Comedy
26067,마음의 소리 스페셜 1-효! 크러쉬,마음의 소리 스페셜 1-효! 크러쉬,8.0,1,0.600,2018-12-31,2018,12,ko,Animation
26042,번개맨의 비밀,번개맨의 비밀,9.0,1,0.600,2018-12-31,2018,12,ko,Animation
25882,유병재: B의 농담,유병재: B의 농담,6.5,2,0.708,2018-08-17,2018,8,ko,Comedy
62567,해양경찰 마르코,해양경찰 마르코,8.0,1,0.600,2013-12-31,2013,12,ko,Comedy
36277,해양경찰 마르코,해양경찰 마르코,8.0,1,0.600,2013-12-31,2013,12,ko,Adventure
9987,해양경찰 마르코,해양경찰 마르코,8.0,1,0.600,2013-12-31,2013,12,ko,Animation

## tmdb_genre_stats table

In [64]:
tmdb_genre_vc = tmdb_movies_genre.groupby('genre')['vote_count'].describe()
tmdb_genre_vc

,count,mean,std,min,25%,50%,75%,max
genre,,,,,,,,
Action,2567.0,712.945462,2098.316280,1.0,4.00,24.0,175.00,22186.0
Adventure,1368.0,1168.625731,2853.210887,1.0,4.00,29.5,420.50,22186.0
Animation,1452.0,304.738292,1163.166918,1.0,2.00,9.0,64.25,12691.0
Comedy,5597.0,238.693050,948.216733,1.0,2.00,9.0,59.00,20175.0
Crime,1484.0,410.179245,1237.899755,1.0,4.00,19.5,176.00,13933.0
Documentary,4945.0,12.559151,40.727434,1.0,1.00,3.0,8.00,713.0
Drama,8207.0,242.684903,953.222677,1.0,3.00,11.0,67.00,18597.0
Family,1538.0,378.999350,1376.421407,1.0,3.00,12.0,61.75,12691.0
Fantasy,1113.0,765.440252,2160.438852,1.0,3.00,20.0,168.00,14587.0
History,611.0,295.702128,933.574584,1.0,2.00,12.0,97.00,10396.0
Horror,3658.0,131.503827,577.410354,1.0,2.00,7.0,32.00,10931.0
Music,1251.0,66.936851,424.604997,1.0,1.00,3.0,11.00,7908.0
Mystery,1223.0,340.786590,1109.963248,1.0,3.50,16.0,108.50,12625.0
Romance,2294.0,264.404098,932.372046,1.0,4.00,14.0,70.00,12566.0
Science Fiction,1743.0,672.269650,2216.988022,1.0,3.00,12.0,81.00,22186.0
TV Movie,1077.0,29.887651,97.619488,1.0,4.00,10.0,22.00,1932.0
Thriller,4165.0,308.690516,1039.459852,1.0,4.00,15.0,103.00,14056.0
War,323.0,402.941176,1434.572839,1.0,3.50,20.0,116.00,12566.0
Western,204.0,454.151961,1811.155283,1.0,1.75,6.5,55.75,15725.0

In [65]:
# reset index
tmdb_genre_vc.reset_index(inplace = True)

In [68]:
mapper = {'count':'movie_count',
         'mean':'vote_count_avg',
         'std':'vote_count_std',}
tmdb_genre_vc.rename(columns = mapper)

,genre,movie_count,vote_count_avg,vote_count_std,min,25%,50%,75%,max
0,Action,2567.0,712.945462,2098.316280,1.0,4.00,24.0,175.00,22186.0
1,Adventure,1368.0,1168.625731,2853.210887,1.0,4.00,29.5,420.50,22186.0
2,Animation,1452.0,304.738292,1163.166918,1.0,2.00,9.0,64.25,12691.0
3,Comedy,5597.0,238.693050,948.216733,1.0,2.00,9.0,59.00,20175.0
4,Crime,1484.0,410.179245,1237.899755,1.0,4.00,19.5,176.00,13933.0
5,Documentary,4945.0,12.559151,40.727434,1.0,1.00,3.0,8.00,713.0
6,Drama,8207.0,242.684903,953.222677,1.0,3.00,11.0,67.00,18597.0
7,Family,1538.0,378.999350,1376.421407,1.0,3.00,12.0,61.75,12691.0
8,Fantasy,1113.0,765.440252,2160.438852,1.0,3.00,20.0,168.00,14587.0
9,History,611.0,295.702128,933.574584,1.0,2.00,12.0,97.00,10396.0
10,Horror,3658.0,131.503827,577.410354,1.0,2.00,7.0,32.00,10931.0
11,Music,1251.0,66.936851,424.604997,1.0,1.00,3.0,11.00,7908.0
12,Mystery,1223.0,340.786590,1109.963248,1.0,3.50,16.0,108.50,12625.0
13,Romance,2294.0,264.404098,932.372046,1.0,4.00,14.0,70.00,12566.0
14,Science Fiction,1743.0,672.269650,2216.988022,1.0,3.00,12.0,81.00,22186.0
15,TV Movie,1077.0,29.887651,97.619488,1.0,4.00,10.0,22.00,1932.0
16,Thriller,4165.0,308.690516,1039.459852,1.0,4.00,15.0,103.00,14056.0
17,War,323.0,402.941176,1434.572839,1.0,3.50,20.0,116.00,12566.0
18,Western,204.0,454.151961,1811.155283,1.0,1.75,6.5,55.75,15725.0

In [66]:
# check 
tmdb_genre_vc

,genre,count,mean,std,min,25%,50%,75%,max
0,Action,2567.0,712.945462,2098.316280,1.0,4.00,24.0,175.00,22186.0
1,Adventure,1368.0,1168.625731,2853.210887,1.0,4.00,29.5,420.50,22186.0
2,Animation,1452.0,304.738292,1163.166918,1.0,2.00,9.0,64.25,12691.0
3,Comedy,5597.0,238.693050,948.216733,1.0,2.00,9.0,59.00,20175.0
4,Crime,1484.0,410.179245,1237.899755,1.0,4.00,19.5,176.00,13933.0
5,Documentary,4945.0,12.559151,40.727434,1.0,1.00,3.0,8.00,713.0
6,Drama,8207.0,242.684903,953.222677,1.0,3.00,11.0,67.00,18597.0
7,Family,1538.0,378.999350,1376.421407,1.0,3.00,12.0,61.75,12691.0
8,Fantasy,1113.0,765.440252,2160.438852,1.0,3.00,20.0,168.00,14587.0
9,History,611.0,295.702128,933.574584,1.0,2.00,12.0,97.00,10396.0
10,Horror,3658.0,131.503827,577.410354,1.0,2.00,7.0,32.00,10931.0
11,Music,1251.0,66.936851,424.604997,1.0,1.00,3.0,11.00,7908.0
12,Mystery,1223.0,340.786590,1109.963248,1.0,3.50,16.0,108.50,12625.0
13,Romance,2294.0,264.404098,932.372046,1.0,4.00,14.0,70.00,12566.0
14,Science Fiction,1743.0,672.269650,2216.988022,1.0,3.00,12.0,81.00,22186.0
15,TV Movie,1077.0,29.887651,97.619488,1.0,4.00,10.0,22.00,1932.0
16,Thriller,4165.0,308.690516,1039.459852,1.0,4.00,15.0,103.00,14056.0
17,War,323.0,402.941176,1434.572839,1.0,3.50,20.0,116.00,12566.0
18,Western,204.0,454.151961,1811.155283,1.0,1.75,6.5,55.75,15725.0

In [70]:
#pd.DataFrame(tmdb_genre_vc['movie_count'].sort_values()).reset_index()

In [71]:
tmdb_movies.shape

(26290, 13)